name: revolt_weather_app
description: An application to retrieve weather data from anywhere in the world.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get: ^3.10.2
  geolocator: ^5.3.2+2
  http: ^0.12.2
  flutter_web_browser: ^0.12.0
  intl: ^0.16.1
  flutter_icons: ^1.1.0
  sleek_circular_slider: ^1.1.0
  flutter_webview_plugin: ^0.3.11
  flutter_map: ^0.10.1+1
  google_maps_flutter: ^1.0.3
  flutter_animation_progress_bar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Light.ttf
          weight: 200
        - asset: fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: fonts/Oxygen-Bold.ttf
          weight: 900
    - family: RedHat
      fonts:
        - asset: fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: fonts/RedHatDisplay-Bold.ttf
          weight: 900



